const technician = [
  {
    name: "Raj Kumar",
    email: "raj.kumar@fixcare.com",
    password: "Raj@12345",
    phone: "9876543210",
    role: "technician",
    status: "active",
    specialization: "AC Repair",
    experience: 4,
  },
  {
    name: "Amit Sharma",
    email: "amit.sharma@fixcare.com",
    password: "Amit@12345",
    phone: "9823456710",
    role: "technician",
    status: "active",
    specialization: "Refrigerator Repair",
    experience: 5,
  },
  {
    name: "Sameer Patil",
    email: "sameer.patil@fixcare.com",
    password: "Sameer@12345",
    phone: "9987654321",
    role: "technician",
    status: "active",
    specialization: "Washing Machine Repair",
    experience: 3,
  },
  {
    name: "Vikas Mehta",
    email: "vikas.mehta@fixcare.com",
    password: "Vikas@12345",
    phone: "9765432109",
    role: "technician",
    status: "active",
    specialization: "TV Repair",
    experience: 6,
  },
  {
    name: "Rohan Singh",
    email: "rohan.singh@fixcare.com",
    password: "Rohan@12345",
    phone: "9898989898",
    role: "technician",
    status: "inactive",
    specialization: "Microwave Repair",
    experience: 2,
  },
];
